spring:
  application:
    name: lv4-kafka
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/ticket_db
    username: ticket_user
    password: ticket_password

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    consumer:
      group-id: ticket-reservation-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      acks: all
      retries: 3

  docker:
    compose:
      file: infra/docker-compose.yml

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
